apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq-secret
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.user }}
  password: {{ .Values.rabbitmq.password }}
  vhost: {{ .Values.rabbitmq.vhost }}
