apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-processor.fullname" . }}
  labels:
    app: api-processor
spec:
  type: {{ .Values.service.type }}
  selector:
    app: api-processor
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

