apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emailer-app.fullname" . }}-db
  labels:
    {{- include "emailer-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.mariadb.user | quote }}
  DB_PASS: {{ .Values.mariadb.password | quote }}
