apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "builder.fullname" . }}
  labels:
    {{- include "builder.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "builder.fullname" . }}-db
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "builder.fullname" . }}-db
                  key: DB_PASS
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dgrails.env={{ .Values.app.grailsEnv }}
                -Dserver.port={{ .Values.service.port }}
                -DdataSource.url=jdbc:mariadb://{{ include "builder.mysqlHost" . }}:3306/{{ .Values.mariadb.database }}
                -DdataSource.username=$(DB_USER)
                -DdataSource.password=$(DB_PASS)
                -DdataSource.driverClassName=org.mariadb.jdbc.Driver
                -Dproduct=EXSITED
                -XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50 -Xms256m -Xmx768m
          readinessProbe:
            tcpSocket: { port: {{ .Values.service.port }} }
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket: { port: {{ .Values.service.port }} }
            initialDelaySeconds: 120
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
