apiVersion: v1
kind: Service
metadata:
  name: {{ include "ps-app.fullname" . }}
  labels:
    {{- include "ps-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: ps-app
    app.kubernetes.io/instance: {{ .Release.Name }}
