apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ps-app.mariadb.fullname" . }}
  labels:
    {{- include "ps-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "ps-app.mariadb.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ps-app.mariadb.fullname" . }}-secret
                  key: mariadb-root-password
            - name: MARIADB_DATABASE
              value: {{ .Values.mariadb.database | quote }}
            - name: MARIADB_USER
              value: {{ .Values.mariadb.user | quote }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ps-app.mariadb.fullname" . }}-secret
                  key: mariadb-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          livenessProbe:
            exec: { command: ["bash","-lc","mysqladmin ping -uroot -p$MARIADB_ROOT_PASSWORD"] }
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec: { command: ["bash","-lc","mysqladmin ping -uroot -p$MARIADB_ROOT_PASSWORD"] }
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mariadb.storage.size | quote }}
        {{- if .Values.mariadb.storage.className }}
        storageClassName: {{ .Values.mariadb.storage.className | quote }}
        {{- end }}
