apiVersion: v1
kind: Service
metadata:
  name: {{ include "ps-app.mariadb.fullname" . }}
  labels:
    {{- include "ps-app.labels" . | nindent 4 }}
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
