apiVersion: v1
kind: Service
metadata:
  name: webhook-mariadb
  labels:
    app: webhook-mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None    # headless service for StatefulSet
  selector:
    app: webhook-mariadb
