apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pdf-service.fullname" . }}
  labels:
    app: pdf-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pdf-service
  template:
    metadata:
      labels:
        app: pdf-service
    spec:
      imagePullSecrets:
        - name: exsited-dockerhub
      containers:
        - name: pdf-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.app.timezone }}
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://{{ include "pdf-service.fullname" . }}-mariadb:3306/{{ .Values.mariadb.database }}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: mariadb-root-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: "com.mysql.cj.jdbc.Driver"

            - name: SPRING_RABBITMQ_HOST
              value: {{ include "pdf-service.fullname" . }}-rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
            - name: SPRING_RABBITMQ_VIRTUAL_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-vhost
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
