apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdf-service.fullname" . }}-mariadb
spec:
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: {{ include "pdf-service.fullname" . }}-mariadb
