apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pdf-service.fullname" . }}-rabbitmq
spec:
  serviceName: {{ include "pdf-service.fullname" . }}-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "pdf-service.fullname" . }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ include "pdf-service.fullname" . }}-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-vhost
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.rabbitmq.persistence.size }}
        storageClassName: {{ .Values.rabbitmq.persistence.storageClass }}
