apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.mariadb.name }}
  ports:
    - port: {{ .Values.mariadb.port }}
      targetPort: {{ .Values.mariadb.port }}
