apiVersion: v1
kind: Service
metadata:
  name: dns-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dns-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
