apiVersion: v1
kind: Service
metadata:
  name: {{ include "email-service.fullname" . }}-mariadb
  labels:
    app: email-service
spec:
  clusterIP: None
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ include "email-service.fullname" . }}-mariadb
