apiVersion: v1
kind: Service
metadata:
  name: {{ include "email-service.fullname" . }}-rabbitmq
  labels:
    app: email-service
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
      {{- if .Values.rabbitmqService.exposeManagementAsNodePort }}
      nodePort: {{ .Values.rabbitmqService.managementNodePort }}
      {{- end }}
  selector:
    app: {{ include "email-service.fullname" . }}-rabbitmq
  type: NodePort
