{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mongo.name }}
  labels:
    {{- include "log-service.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.mongo.name }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.mongo.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.mongo.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          ports:
            - name: mongo
              containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            - name: data
              mountPath: /data/db
          resources:
            {{- toYaml .Values.mongo.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: {{ toYaml .Values.mongo.persistence.accessModes | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.mongo.persistence.size }}
        {{- if .Values.mongo.persistence.storageClassName }}
        storageClassName: "{{ .Values.mongo.persistence.storageClassName }}"
        {{- end }}
{{- end }}
